/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    'audit-log': AuditLog;
    media: Media;
    seasons: Season;
    venues: Venue;
    opponents: Opponent;
    teams: Team;
    staff: Staff;
    players: Player;
    games: Game;
    tournaments: Tournament;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    opponents: OpponentsSelect<false> | OpponentsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path without the locale prefix, e.g. "imprint". Localized per language.
   */
  slug: string;
  blocks?: (HeroCompactBlock | RichTextBlock | CTABannerBlock | DividerBlock)[] | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCompactBlock".
 */
export interface HeroCompactBlock {
  kicker?: string | null;
  title: string;
  lead?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Anchor, background, spacing and visibility for this block.
   */
  settings?: {
    background?: ('default' | 'muted' | 'inverted' | 'accent') | null;
    spacing?: ('none' | 's' | 'm' | 'l') | null;
    /**
     * Enables in-page anchors such as /federation#squad.
     */
    anchorId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroCompact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Anchor, background, spacing and visibility for this block.
   */
  settings?: {
    background?: ('default' | 'muted' | 'inverted' | 'accent') | null;
    spacing?: ('none' | 's' | 'm' | 'l') | null;
    /**
     * Enables in-page anchors such as /federation#squad.
     */
    anchorId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock".
 */
export interface CTABannerBlock {
  title: string;
  lead?: string | null;
  buttons?:
    | {
        label: string;
        href: string;
        variant?: ('primary' | 'secondary' | 'ghost') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Anchor, background, spacing and visibility for this block.
   */
  settings?: {
    background?: ('default' | 'muted' | 'inverted' | 'accent') | null;
    spacing?: ('none' | 's' | 'm' | 'l') | null;
    /**
     * Enables in-page anchors such as /federation#squad.
     */
    anchorId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  variant?: ('line' | 'space') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Permissions are the union of all assigned roles.
   */
  roles: ('superadmin' | 'editor' | 'author' | 'sports_manager' | 'media_manager' | 'translator' | 'viewer')[];
  /**
   * Mandatory for superadmin and editor. TOTP enrolment is pending; this field tracks status.
   */
  twoFactorEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'publish' | 'unpublish' | 'delete' | 'role_change' | 'settings_change' | 'login_failed';
  /**
   * Responsible user
   */
  actor?: (number | null) | User;
  actorEmail?: string | null;
  collectionSlug: string;
  documentId?: string | null;
  documentLabel?: string | null;
  changedFields?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Photographer or source. Mandatory before publishing player photos.
   */
  credit?: string | null;
  license?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * e.g. "2026/27"
   */
  name: string;
  startDate?: string | null;
  endDate?: string | null;
  isCurrent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  city: string;
  address?: string | null;
  /**
   * Search text for the "open in maps app" link, if different from name + city.
   */
  mapQuery?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opponents".
 */
export interface Opponent {
  id: number;
  name: string;
  /**
   * e.g. "Norway"
   */
  shortName: string;
  /**
   * 3-letter placeholder crest code, e.g. "NOR".
   */
  crestCode: string;
  country?: string | null;
  /**
   * Hex value for the crest ring.
   */
  accent?: string | null;
  website?: string | null;
  crest?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * URL path, e.g. "herren". Localized per language.
   */
  slug: string;
  gender: 'herren' | 'damen' | 'nachwuchs';
  ageGroup?: string | null;
  crestCode: string;
  shortName: string;
  /**
   * Hex value.
   */
  accent?: string | null;
  crest?: (number | null) | Media;
  coach?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  /**
   * e.g. "Head coach"
   */
  role: string;
  team: number | Team;
  portrait?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * URL path, e.g. "jan-kowalski". SHOULD be identical in both locales.
   */
  slug: string;
  team: number | Team;
  number: number;
  position: 'TW' | 'VER' | 'MF' | 'ST';
  /**
   * Season-by-season squad history. The current assignment is the "Team" field above.
   */
  memberships?:
    | {
        season: number | Season;
        team: number | Team;
        id?: string | null;
      }[]
    | null;
  playerStatus: 'active' | 'injured' | 'inactive' | 'alumni';
  captain?: boolean | null;
  nationality?: string | null;
  birthYear?: number | null;
  joinedYear?: number | null;
  heightCm?: number | null;
  weightKg?: number | null;
  club?: string | null;
  /**
   * Cut-out portrait, transparent, 3:4. Without an image the jersey number is shown instead.
   */
  portrait?: (number | null) | Media;
  /**
   * Leave empty if no profile text exists yet — the section is then omitted.
   */
  bio?: string | null;
  stats?: {
    caps?: number | null;
    goals?: number | null;
    assists?: number | null;
  };
  /**
   * Set when the biography text was drafted with the editorial assistant.
   */
  aiAssisted?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  /**
   * e.g. "2027-01-16-deutschland-finnland".
   */
  slug: string;
  kickoff: string;
  gameStatus: 'scheduled' | 'live' | 'finished' | 'postponed' | 'cancelled';
  competition: {
    name: string;
    kind: 'friendly' | 'tournament' | 'qualifier' | 'league';
  };
  round?: string | null;
  home:
    | {
        relationTo: 'teams';
        value: number | Team;
      }
    | {
        relationTo: 'opponents';
        value: number | Opponent;
      };
  away:
    | {
        relationTo: 'teams';
        value: number | Team;
      }
    | {
        relationTo: 'opponents';
        value: number | Opponent;
      };
  homeScore?: number | null;
  awayScore?: number | null;
  halftime?: {
    home?: number | null;
    away?: number | null;
  };
  venue: number | Venue;
  isTournamentGame?: boolean | null;
  tournament?: (number | null) | Tournament;
  /**
   * Tournament games only, e.g. "Saturday · Semi-finals".
   */
  tournamentDayLabel?: string | null;
  liveMinute?: number | null;
  postponedTo?: string | null;
  cancellationReason?: string | null;
  ticketUrl?: string | null;
  roster?: {
    submitted?: boolean | null;
    home?: {
      coach?: string | null;
      formation?: string | null;
      players?:
        | {
            player?: (number | null) | Player;
            firstName: string;
            lastName: string;
            number: number;
            position: 'TW' | 'VER' | 'MF' | 'ST';
            starter?: boolean | null;
            captain?: boolean | null;
            events?:
              | {
                  type: 'goal' | 'assist' | 'penalty';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
      bench?: string[] | null;
    };
    away?: {
      coach?: string | null;
      formation?: string | null;
      players?:
        | {
            player?: (number | null) | Player;
            firstName: string;
            lastName: string;
            number: number;
            position: 'TW' | 'VER' | 'MF' | 'ST';
            starter?: boolean | null;
            captain?: boolean | null;
            events?:
              | {
                  type: 'goal' | 'assist' | 'penalty';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
      bench?: string[] | null;
    };
  };
  report?: {
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pullQuote?: string | null;
  };
  events?:
    | {
        minute: number;
        type: 'goal' | 'penalty' | 'card' | 'info';
        side: 'home' | 'away';
        title: string;
        runningHome?: number | null;
        runningAway?: number | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        label: string;
        home: number;
        away: number;
        id?: string | null;
      }[]
    | null;
  referee?: string | null;
  attendance?: number | null;
  weatherNote?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  name: string;
  slug: string;
  type: 'weltmeisterschaft' | 'pokal' | 'liga' | 'qualifikation' | 'turnier' | 'sonstiges';
  format: string;
  startDate: string;
  endDate: string;
  venue: number | Venue;
  hero?: (number | null) | Media;
  participants?:
    | {
        name: string;
        host?: boolean | null;
        /**
         * Disable while the participant is still open (e.g. "Winner SF1").
         */
        resolved?: boolean | null;
        id?: string | null;
      }[]
    | null;
  rules?: string[] | null;
  weatherNote?: string | null;
  /**
   * For the tournament archive and the timeline on /federation.
   */
  placement?: string | null;
  /**
   * Exactly one tournament can show its table on the fixtures page.
   */
  featuredStandings?: boolean | null;
  /**
   * Leave empty when this tournament has no table (e.g. a knockout cup).
   */
  standings?: {
    preseason?: boolean | null;
    note?: string | null;
    rows?:
      | {
          rank: number;
          teamName: string;
          isGermany?: boolean | null;
          played: number;
          win: number;
          draw: number;
          loss: number;
          goalsFor: number;
          goalsAgainst: number;
          points: number;
          zone?: ('qualify' | 'relegate') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'opponents';
        value: number | Opponent;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        heroCompact?: T | HeroCompactBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        ctaBanner?: T | CTABannerBlockSelect<T>;
        divider?: T | DividerBlockSelect<T>;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCompactBlock_select".
 */
export interface HeroCompactBlockSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        anchorId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        anchorId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock_select".
 */
export interface CTABannerBlockSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        anchorId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock_select".
 */
export interface DividerBlockSelect<T extends boolean = true> {
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  twoFactorEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  actorEmail?: T;
  collectionSlug?: T;
  documentId?: T;
  documentLabel?: T;
  changedFields?:
    | T
    | {
        name?: T;
        id?: T;
      };
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  address?: T;
  mapQuery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opponents_select".
 */
export interface OpponentsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  crestCode?: T;
  country?: T;
  accent?: T;
  website?: T;
  crest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  gender?: T;
  ageGroup?: T;
  crestCode?: T;
  shortName?: T;
  accent?: T;
  crest?: T;
  coach?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  team?: T;
  portrait?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  slug?: T;
  team?: T;
  number?: T;
  position?: T;
  memberships?:
    | T
    | {
        season?: T;
        team?: T;
        id?: T;
      };
  playerStatus?: T;
  captain?: T;
  nationality?: T;
  birthYear?: T;
  joinedYear?: T;
  heightCm?: T;
  weightKg?: T;
  club?: T;
  portrait?: T;
  bio?: T;
  stats?:
    | T
    | {
        caps?: T;
        goals?: T;
        assists?: T;
      };
  aiAssisted?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  slug?: T;
  kickoff?: T;
  gameStatus?: T;
  competition?:
    | T
    | {
        name?: T;
        kind?: T;
      };
  round?: T;
  home?: T;
  away?: T;
  homeScore?: T;
  awayScore?: T;
  halftime?:
    | T
    | {
        home?: T;
        away?: T;
      };
  venue?: T;
  isTournamentGame?: T;
  tournament?: T;
  tournamentDayLabel?: T;
  liveMinute?: T;
  postponedTo?: T;
  cancellationReason?: T;
  ticketUrl?: T;
  roster?:
    | T
    | {
        submitted?: T;
        home?:
          | T
          | {
              coach?: T;
              formation?: T;
              players?:
                | T
                | {
                    player?: T;
                    firstName?: T;
                    lastName?: T;
                    number?: T;
                    position?: T;
                    starter?: T;
                    captain?: T;
                    events?:
                      | T
                      | {
                          type?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              bench?: T;
            };
        away?:
          | T
          | {
              coach?: T;
              formation?: T;
              players?:
                | T
                | {
                    player?: T;
                    firstName?: T;
                    lastName?: T;
                    number?: T;
                    position?: T;
                    starter?: T;
                    captain?: T;
                    events?:
                      | T
                      | {
                          type?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              bench?: T;
            };
      };
  report?:
    | T
    | {
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pullQuote?: T;
      };
  events?:
    | T
    | {
        minute?: T;
        type?: T;
        side?: T;
        title?: T;
        runningHome?: T;
        runningAway?: T;
        detail?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        home?: T;
        away?: T;
        id?: T;
      };
  referee?: T;
  attendance?: T;
  weatherNote?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  format?: T;
  startDate?: T;
  endDate?: T;
  venue?: T;
  hero?: T;
  participants?:
    | T
    | {
        name?: T;
        host?: T;
        resolved?: T;
        id?: T;
      };
  rules?: T;
  weatherNote?: T;
  placement?: T;
  featuredStandings?: T;
  standings?:
    | T
    | {
        preseason?: T;
        note?: T;
        rows?:
          | T
          | {
              rank?: T;
              teamName?: T;
              isGermany?: T;
              played?: T;
              win?: T;
              draw?: T;
              loss?: T;
              goalsFor?: T;
              goalsAgainst?: T;
              points?: T;
              zone?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  nav?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              children?:
                | {
                    label: string;
                    href: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  organizationName?: string | null;
  contactEmail?: string | null;
  social?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * %s is replaced by the page title.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  tagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationName?: T;
  contactEmail?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  defaultDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}